DROP TABLE IF EXISTS POSTS;

CREATE TABLE POSTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT 1,
  tags BLOB NULL DEFAULT '[]'
);
